plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Project: deus-dashboard
  instance-state-name: running
keyed_groups:
  - key: tags.Role
    prefix: role
compose:
  ansible_host: private_ip_address
