[bastion]
35.173.122.117 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/vockey.pem

[ecs_instances]
10.0.10.74 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/vockey.pem

[monitoring]
10.0.1.249 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/vockey.pem

[ecs_instances:vars]
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/vockey.pem -o StrictHostKeyChecking=no ec2-user@35.173.122.117"

[monitoring:vars]
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/vockey.pem -o StrictHostKeyChecking=no ec2-user@35.173.122.117"
