---
- name: Configure ECS EC2 instances
  hosts: ecs_instances
  become: true
  vars:
    ecs_cluster_name: deus-dashboard-dev
    aws_region: us-east-1
  roles:
    - security
    - docker
    - ecs-agent
    - cloudwatch-agent
